import Head from 'next/head'
import AppList from './components/AppList';
import useAuthRedirect from '@/hooks/useAuthRedirect';

export default function List() {
  useAuthRedirect('/login');
  return (
    <>
      <Head>
        <title>List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppList />
    </>
  )
}
