import Head from 'next/head'
import useAuthRedirect from '@/hooks/useAuthRedirect';
import SettingsForm from './components/SettingsForm'

export default function Settings() {
  useAuthRedirect('/login');
  return (
    <>
      <Head>
        <title>Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SettingsForm />
    </>
  )
}
