import Head from 'next/head'
import AppList from '../components/applist';
import { Spinner } from '@chakra-ui/react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';

export default function Username() {
  const supabaseClient = useSupabaseClient();
  const router = useRouter();
  const { username } = router.query;

  const [userId, setUserId] = useState(null)

  useEffect(() => {
    async function getUserId() {
      let query = supabaseClient.from('user_details').select().eq('username', username)
      const { data, error } = await query;
      setUserId(data[0].user_id);
    }
    if (username) getUserId();
  }, [username])

  return (
    <>
      <Head>
        <title>List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {userId ? <AppList userId={userId} /> : <Spinner />}
    </>
  )
}
